/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.interfaz;

import com.DataBase.Acciones;
import com.backend.Botones;

/**
 *
 * @author marlo
 */
public class Menu extends javax.swing.JFrame {

    private final Botones btn = new Botones();
    private final Acciones ac = new Acciones();
    /**
     * Creates new form EnConstruccion
     */
    public Menu() {
        initComponents();
    }

    public void nombreUsuario(String nombre) {
        jlblNombreUsuarioMenu.setText(nombre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpInterzfaz = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jpPerfil = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jpAgregar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jpEditar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jpEliminar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jpReportes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtpOpciones = new javax.swing.JTabbedPane();
        jPanelPerfil = new javax.swing.JPanel();
        jlblNombreUsuarioMenu = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpCambiarContrasena = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanelEditarContrasena = new javax.swing.JPanel();
        jpBotonGuardarContrasena = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jpBotonCancelarContrasena = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jpswConfirmarContrasena = new javax.swing.JPasswordField();
        jpswContrasenaAnterior = new javax.swing.JPasswordField();
        jpswContrasenaNueva = new javax.swing.JPasswordField();
        jLabel37 = new javax.swing.JLabel();
        jlblTextoErrorContrasenaDiferente = new javax.swing.JLabel();
        jlblTextoErrorContrasenaIngresada = new javax.swing.JLabel();
        jPanelAgregar = new javax.swing.JPanel();
        jpAceptarAgregar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpCancelarAgregar = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jPanelEditar = new javax.swing.JPanel();
        jpAceptarEditar = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jpCancelarEditar = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanelEliminar = new javax.swing.JPanel();
        jpAceptarEliminar = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jpCancelarEliminar = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanelReportes = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpInterzfaz.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpPerfil.setBackground(new java.awt.Color(75, 77, 102));
        jpPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpPerfil.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Perfil");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });
        jpPerfil.add(jLabel6, java.awt.BorderLayout.CENTER);

        jpMenu.add(jpPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 120));

        jpAgregar.setBackground(new java.awt.Color(75, 77, 102));
        jpAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jpAgregar.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Agregar Alimento");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        jpAgregar.add(jLabel7, java.awt.BorderLayout.CENTER);

        jpMenu.add(jpAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 240, 120));

        jpEditar.setBackground(new java.awt.Color(75, 77, 102));
        jpEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpEditar.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Editar Alimento");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        jpEditar.add(jLabel8, java.awt.BorderLayout.CENTER);

        jpMenu.add(jpEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 120));

        jpEliminar.setBackground(new java.awt.Color(75, 77, 102));
        jpEliminar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpEliminar.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Eliminar Alimento");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
        });
        jpEliminar.add(jLabel9, java.awt.BorderLayout.CENTER);

        jpMenu.add(jpEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 240, 120));

        jpReportes.setBackground(new java.awt.Color(75, 77, 102));
        jpReportes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpReportes.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Reportes");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        jpReportes.add(jLabel10, java.awt.BorderLayout.CENTER);

        jpMenu.add(jpReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 240, 120));

        jpInterzfaz.add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        jtpOpciones.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanelPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPerfil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblNombreUsuarioMenu.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 50)); // NOI18N
        jlblNombreUsuarioMenu.setForeground(new java.awt.Color(75, 77, 102));
        jlblNombreUsuarioMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreUsuarioMenu.setText("Aa");
        jPanelPerfil.add(jlblNombreUsuarioMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 400, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(75, 77, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Bienvenido: ");
        jPanelPerfil.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 300, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/SplashAdmin.png"))); // NOI18N
        jPanelPerfil.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 200, 190));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(77, 71, 83));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("EAT");
        jPanelPerfil.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 220, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(77, 71, 83));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("WELL");
        jPanelPerfil.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 220, -1));

        jpCambiarContrasena.setBackground(new java.awt.Color(86, 117, 184));
        jpCambiarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpCambiarContrasenaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpCambiarContrasenaMouseExited(evt);
            }
        });
        jpCambiarContrasena.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Cambiar Contraseña");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        jpCambiarContrasena.add(jLabel11, java.awt.BorderLayout.CENTER);

        jPanelPerfil.add(jpCambiarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 260, 50));

        jtpOpciones.addTab("tab1", jPanelPerfil);

        jPanelEditarContrasena.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEditarContrasena.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpBotonGuardarContrasena.setBackground(new java.awt.Color(86, 117, 184));
        jpBotonGuardarContrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpBotonGuardarContrasenaMouseEntered(evt);
            }
        });
        jpBotonGuardarContrasena.setLayout(new java.awt.BorderLayout());

        jLabel23.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Guardar");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel23MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel23MouseExited(evt);
            }
        });
        jpBotonGuardarContrasena.add(jLabel23, java.awt.BorderLayout.CENTER);

        jPanelEditarContrasena.add(jpBotonGuardarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 260, 50));

        jLabel19.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(75, 77, 102));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Confirmar Contraseña:");
        jPanelEditarContrasena.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 410, -1));

        jLabel21.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(75, 77, 102));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Editar Contraseña");
        jPanelEditarContrasena.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 380, -1));

        jLabel22.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(75, 77, 102));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Contraseña Nueva:");
        jPanelEditarContrasena.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 380, -1));

        jpBotonCancelarContrasena.setBackground(new java.awt.Color(86, 117, 184));
        jpBotonCancelarContrasena.setLayout(new java.awt.BorderLayout());

        jLabel18.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Cancelar");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        jpBotonCancelarContrasena.add(jLabel18, java.awt.BorderLayout.CENTER);

        jPanelEditarContrasena.add(jpBotonCancelarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 260, 50));

        jpswConfirmarContrasena.setBackground(new java.awt.Color(77, 71, 83));
        jpswConfirmarContrasena.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jpswConfirmarContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jpswConfirmarContrasena.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanelEditarContrasena.add(jpswConfirmarContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 320, -1));

        jpswContrasenaAnterior.setBackground(new java.awt.Color(77, 71, 83));
        jpswContrasenaAnterior.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jpswContrasenaAnterior.setForeground(new java.awt.Color(255, 255, 255));
        jpswContrasenaAnterior.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jpswContrasenaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpswContrasenaAnteriorActionPerformed(evt);
            }
        });
        jPanelEditarContrasena.add(jpswContrasenaAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 320, -1));

        jpswContrasenaNueva.setBackground(new java.awt.Color(77, 71, 83));
        jpswContrasenaNueva.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jpswContrasenaNueva.setForeground(new java.awt.Color(255, 255, 255));
        jpswContrasenaNueva.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanelEditarContrasena.add(jpswContrasenaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 320, -1));

        jLabel37.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 40)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(75, 77, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel37.setText("Contraseña anterior:");
        jPanelEditarContrasena.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, -1));

        jlblTextoErrorContrasenaDiferente.setBackground(new java.awt.Color(255, 0, 0));
        jlblTextoErrorContrasenaDiferente.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jlblTextoErrorContrasenaDiferente.setForeground(new java.awt.Color(255, 0, 0));
        jPanelEditarContrasena.add(jlblTextoErrorContrasenaDiferente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 270, 20));

        jlblTextoErrorContrasenaIngresada.setBackground(new java.awt.Color(255, 0, 0));
        jlblTextoErrorContrasenaIngresada.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        jlblTextoErrorContrasenaIngresada.setForeground(new java.awt.Color(255, 0, 0));
        jPanelEditarContrasena.add(jlblTextoErrorContrasenaIngresada, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 270, 20));

        jtpOpciones.addTab("tab2", jPanelEditarContrasena);

        jPanelAgregar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAgregar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpAceptarAgregar.setBackground(new java.awt.Color(86, 117, 184));
        jpAceptarAgregar.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Aceptar");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel14MouseExited(evt);
            }
        });
        jpAceptarAgregar.add(jLabel14, java.awt.BorderLayout.CENTER);

        jPanelAgregar.add(jpAceptarAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 260, 50));

        jpCancelarAgregar.setBackground(new java.awt.Color(86, 117, 184));
        jpCancelarAgregar.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Cancelar");
        jLabel15.setToolTipText("");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel15MouseExited(evt);
            }
        });
        jpCancelarAgregar.add(jLabel15, java.awt.BorderLayout.CENTER);

        jPanelAgregar.add(jpCancelarAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 260, 50));

        jLabel16.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(75, 77, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Grupos");
        jPanelAgregar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 140, 50));

        jLabel17.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(75, 77, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Agregar Alimento");
        jPanelAgregar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 280, 50));

        jLabel20.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(75, 77, 102));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Nombre:");
        jPanelAgregar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 50));

        jLabel24.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(75, 77, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Calorias:");
        jPanelAgregar.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 50));

        jTextField2.setBackground(new java.awt.Color(75, 77, 102));
        jTextField2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 450, 50));

        jFormattedTextField1.setBackground(new java.awt.Color(75, 77, 102));
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelAgregar.add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 450, 50));

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox1.setText("Verduras");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 160, -1));

        jCheckBox2.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox2.setText("Bebidas");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 160, -1));

        jCheckBox3.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox3.setText("Grano");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 160, -1));

        jCheckBox4.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox4.setText("Fruta");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));

        jCheckBox5.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox5.setText("Proteinas");
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 160, -1));

        jCheckBox6.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox6.setText("Lacteos");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanelAgregar.add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 160, -1));

        jtpOpciones.addTab("tab3", jPanelAgregar);

        jPanelEditar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEditar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpAceptarEditar.setBackground(new java.awt.Color(86, 117, 184));
        jpAceptarEditar.setLayout(new java.awt.BorderLayout());

        jLabel25.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Aceptar");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel25MouseExited(evt);
            }
        });
        jpAceptarEditar.add(jLabel25, java.awt.BorderLayout.CENTER);

        jPanelEditar.add(jpAceptarEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 260, 50));

        jpCancelarEditar.setBackground(new java.awt.Color(86, 117, 184));
        jpCancelarEditar.setLayout(new java.awt.BorderLayout());

        jLabel26.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Cancelar");
        jLabel26.setToolTipText("");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel26MouseExited(evt);
            }
        });
        jpCancelarEditar.add(jLabel26, java.awt.BorderLayout.CENTER);

        jPanelEditar.add(jpCancelarEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 260, 50));

        jLabel27.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(75, 77, 102));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Grupos");
        jPanelEditar.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 140, 50));

        jLabel28.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(75, 77, 102));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Editar Alimento");
        jPanelEditar.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 280, 50));

        jLabel29.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(75, 77, 102));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Nombre:");
        jPanelEditar.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 140, 50));

        jLabel30.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(75, 77, 102));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("Calorias:");
        jPanelEditar.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 140, 50));

        jFormattedTextField2.setBackground(new java.awt.Color(75, 77, 102));
        jFormattedTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jPanelEditar.add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 450, 50));

        jCheckBox7.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox7.setText("Verduras");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });
        jPanelEditar.add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 160, -1));

        jCheckBox8.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox8.setText("Bebidas");
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jPanelEditar.add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, 160, -1));

        jCheckBox9.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox9.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox9.setText("Grano");
        jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox9ActionPerformed(evt);
            }
        });
        jPanelEditar.add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 160, -1));

        jCheckBox10.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox10.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox10.setText("Fruta");
        jCheckBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox10ActionPerformed(evt);
            }
        });
        jPanelEditar.add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 160, -1));

        jCheckBox11.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox11.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox11.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox11.setText("Proteinas");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanelEditar.add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 160, -1));

        jCheckBox12.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBox12.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jCheckBox12.setForeground(new java.awt.Color(75, 77, 102));
        jCheckBox12.setText("Lacteos");
        jCheckBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox12ActionPerformed(evt);
            }
        });
        jPanelEditar.add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, 160, -1));

        jComboBox1.setBackground(new java.awt.Color(75, 77, 102));
        jComboBox1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelEditar.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 450, 50));

        jtpOpciones.addTab("tab4", jPanelEditar);

        jPanelEliminar.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpAceptarEliminar.setBackground(new java.awt.Color(86, 117, 184));
        jpAceptarEliminar.setLayout(new java.awt.BorderLayout());

        jLabel31.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Aceptar");
        jLabel31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel31MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel31MouseExited(evt);
            }
        });
        jpAceptarEliminar.add(jLabel31, java.awt.BorderLayout.CENTER);

        jPanelEliminar.add(jpAceptarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, 260, 50));

        jpCancelarEliminar.setBackground(new java.awt.Color(86, 117, 184));
        jpCancelarEliminar.setLayout(new java.awt.BorderLayout());

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Cancelar");
        jLabel32.setToolTipText("");
        jLabel32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel32MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel32MouseExited(evt);
            }
        });
        jpCancelarEliminar.add(jLabel32, java.awt.BorderLayout.CENTER);

        jPanelEliminar.add(jpCancelarEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 260, 50));

        jLabel34.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(75, 77, 102));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Eliminar Alimento");
        jPanelEliminar.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 280, 50));

        jLabel35.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(75, 77, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("Nombre:");
        jPanelEliminar.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 140, 50));

        jComboBox2.setBackground(new java.awt.Color(75, 77, 102));
        jComboBox2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 30)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanelEliminar.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 450, 50));

        jtpOpciones.addTab("tab5", jPanelEliminar);

        jPanelReportes.setLayout(new java.awt.BorderLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/Pagina-en-construccion.jpg"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanelReportes.add(jLabel13, java.awt.BorderLayout.CENTER);

        jtpOpciones.addTab("tab6", jPanelReportes);

        jpInterzfaz.add(jtpOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 820, 600));
        jtpOpciones.getAccessibleContext().setAccessibleName("tabContrasena");

        getContentPane().add(jpInterzfaz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox12ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jCheckBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox10ActionPerformed

    private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox9ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCambiarContrasena, 0);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jpCambiarContrasenaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCambiarContrasenaMouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCambiarContrasena, 0);
    }//GEN-LAST:event_jpCambiarContrasenaMouseExited

    private void jpCambiarContrasenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpCambiarContrasenaMouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCambiarContrasena, 1);
    }//GEN-LAST:event_jpCambiarContrasenaMouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCambiarContrasena, 1);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpPerfil, 1);
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpPerfil, 0);
    }//GEN-LAST:event_jLabel6MouseExited

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpAgregar, 1);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpAgregar, 0);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpEditar, 1);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpEditar, 0);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpEliminar, 1);
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpEliminar, 0);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpReportes, 1);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotonesMenu(jpReportes, 0);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel23MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpBotonGuardarContrasena, 0);
    }//GEN-LAST:event_jLabel23MouseEntered

    private void jLabel23MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpBotonGuardarContrasena, 1);
    }//GEN-LAST:event_jLabel23MouseExited

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpBotonCancelarContrasena, 0);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpBotonCancelarContrasena, 1);
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarPestañaMenu(jtpOpciones, 0);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarPestañaMenu(jtpOpciones, 2);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarPestañaMenu(jtpOpciones, 3);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarPestañaMenu(jtpOpciones, 4);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarPestañaMenu(jtpOpciones, 5);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarPestañaMenu(jtpOpciones, 1);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        // TODO add your handling code here:
        this.ac.limpiarCambioContraseña(jlblTextoErrorContrasenaIngresada, jlblTextoErrorContrasenaDiferente, jpswContrasenaAnterior, jpswContrasenaNueva, jpswConfirmarContrasena);
        this.ac.cambiarPestañaMenu(jtpOpciones, 0);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jpBotonGuardarContrasenaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpBotonGuardarContrasenaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpBotonGuardarContrasenaMouseEntered

    private void jpswContrasenaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpswContrasenaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpswContrasenaAnteriorActionPerformed

    private void jLabel14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpAceptarAgregar, 0);
    }//GEN-LAST:event_jLabel14MouseEntered

    private void jLabel14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpAceptarAgregar, 1);
    }//GEN-LAST:event_jLabel14MouseExited

    private void jLabel15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCancelarAgregar, 0);
    }//GEN-LAST:event_jLabel15MouseEntered

    private void jLabel15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCancelarAgregar, 1);
    }//GEN-LAST:event_jLabel15MouseExited

    private void jLabel25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpAceptarEditar, 0);
    }//GEN-LAST:event_jLabel25MouseEntered

    private void jLabel25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpAceptarEditar, 1);
    }//GEN-LAST:event_jLabel25MouseExited

    private void jLabel26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCancelarEditar, 0);
    }//GEN-LAST:event_jLabel26MouseEntered

    private void jLabel26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCancelarEditar, 1);
    }//GEN-LAST:event_jLabel26MouseExited

    private void jLabel31MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpAceptarEliminar, 0);
    }//GEN-LAST:event_jLabel31MouseEntered

    private void jLabel31MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpAceptarEliminar,1);
    }//GEN-LAST:event_jLabel31MouseExited

    private void jLabel32MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseEntered
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCancelarEliminar, 0);
    }//GEN-LAST:event_jLabel32MouseEntered

    private void jLabel32MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseExited
        // TODO add your handling code here:
        this.btn.cambiarColorBotones(jpCancelarEliminar, 1);
    }//GEN-LAST:event_jLabel32MouseExited

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        // TODO add your handling code here:
        this.ac.cambiarContraseña(jlblNombreUsuarioMenu.getText(), jlblTextoErrorContrasenaIngresada, jlblTextoErrorContrasenaDiferente, jpswContrasenaAnterior, jpswContrasenaNueva, jpswConfirmarContrasena);
    }//GEN-LAST:event_jLabel23MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelAgregar;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelEditarContrasena;
    private javax.swing.JPanel jPanelEliminar;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JPanel jPanelReportes;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlblNombreUsuarioMenu;
    private javax.swing.JLabel jlblTextoErrorContrasenaDiferente;
    private javax.swing.JLabel jlblTextoErrorContrasenaIngresada;
    private javax.swing.JPanel jpAceptarAgregar;
    private javax.swing.JPanel jpAceptarEditar;
    private javax.swing.JPanel jpAceptarEliminar;
    private javax.swing.JPanel jpAgregar;
    private javax.swing.JPanel jpBotonCancelarContrasena;
    private javax.swing.JPanel jpBotonGuardarContrasena;
    private javax.swing.JPanel jpCambiarContrasena;
    private javax.swing.JPanel jpCancelarAgregar;
    private javax.swing.JPanel jpCancelarEditar;
    private javax.swing.JPanel jpCancelarEliminar;
    private javax.swing.JPanel jpEditar;
    private javax.swing.JPanel jpEliminar;
    private javax.swing.JPanel jpInterzfaz;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpPerfil;
    private javax.swing.JPanel jpReportes;
    private javax.swing.JPasswordField jpswConfirmarContrasena;
    private javax.swing.JPasswordField jpswContrasenaAnterior;
    private javax.swing.JPasswordField jpswContrasenaNueva;
    private javax.swing.JTabbedPane jtpOpciones;
    // End of variables declaration//GEN-END:variables
}
